// @ts-nocheck
'use client';
import { Node,Extension,mergeAttributes } from '@tiptap/core';
import { NodeViewWrapper,NodeViewContent,ReactNodeViewRenderer,type NodeViewProps } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import TextAlign from '@tiptap/extension-text-align';
import {TableKit} from '@tiptap/extension-table';
import CodeBlockLowlight from '@tiptap/extension-code-block-lowlight';
import {common,createLowlight} from 'lowlight';
import {Plugin} from '@tiptap/pm/state';
import {Copy,Check,Info,TriangleAlert} from 'lucide-react';
import {useState} from 'react';
import {safeLink} from '@/lib/document';
export const languages=[['text','Текст'],['json','JSON'],['javascript','JavaScript'],['typescript','TypeScript'],['html','HTML'],['css','CSS'],['bash','Bash / cURL'],['python','Python'],['php','PHP'],['java','Java'],['csharp','C#'],['go','Go'],['ruby','Ruby'],['sql','SQL'],['xml','XML'],['yaml','YAML']];
function CodeView({node}:NodeViewProps){const [copied,setCopied]=useState(false);return <NodeViewWrapper className="code-node"><div contentEditable={false} className="code-toolbar"><span>{languages.find(([id])=>id===node.attrs.language)?.[1]||node.attrs.language||'Текст'}</span><button type="button" aria-label="Копировать код" title="Копировать код" onClick={async()=>{try{await navigator.clipboard.writeText(node.textContent);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setCopied(false);}}}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><pre><NodeViewContent as="code"/></pre></NodeViewWrapper>;}
function CalloutView({node}:NodeViewProps){return <NodeViewWrapper className={'callout-node '+(node.attrs.kind==='attention'?'attention':'info')}><div className="callout-label" contentEditable={false}>{node.attrs.kind==='attention'?<TriangleAlert size={18}/>:<Info size={18}/>}<span>{node.attrs.kind==='attention'?'Attention':'Информация'}</span></div><NodeViewContent className="callout-body"/></NodeViewWrapper>;}
function ButtonView({node,selected}:NodeViewProps){const a=node.attrs;return <NodeViewWrapper className={'button-node '+(selected?'selected':'')} style={{textAlign:a.align||'center'}}><span className="document-button" style={{width:a.fullWidth?'100%':Number(a.width)||240,minHeight:Number(a.height)||56,fontSize:Number(a.fontSize)||18}}>{a.label||'Кнопка'}</span></NodeViewWrapper>;}
const Callout=Node.create({name:'callout',group:'block',content:'block+',defining:true,isolating:true,addAttributes(){return {kind:{default:'info',parseHTML:el=>el.getAttribute('data-kind')||(el.classList.contains('warning')?'attention':'info')}};},parseHTML(){return [{tag:'div[data-type="callout"]'},{tag:'aside[data-type="callout"]'},{tag:'aside.api-callout'}];},renderHTML({HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{'data-type':'callout','data-kind':HTMLAttributes.kind}),0];},addNodeView(){return ReactNodeViewRenderer(CalloutView);}});
const DocButton=Node.create({name:'docButton',group:'block',atom:true,draggable:true,selectable:true,addAttributes(){return Object.fromEntries(Object.entries({label:'Кнопка',href:'https://cloudpayments.ru/',width:240,height:56,fontSize:18,align:'center',fullWidth:false}).map(([name,value])=>[name,{default:value,parseHTML:(el:HTMLElement)=>{const v=el.getAttribute('data-'+name.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()));return v===null?value:typeof value==='number'?Number(v):typeof value==='boolean'?v==='true':v;}}]));},parseHTML(){return [{tag:'div[data-type="doc-button"]'}];},renderHTML({HTMLAttributes:a}){return ['div',{'data-type':'doc-button',...Object.fromEntries(Object.entries(a).map(([k,v])=>['data-'+k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()),String(v)]))},['a',{href:safeLink(a.href)},a.label]];},addNodeView(){return ReactNodeViewRenderer(ButtonView);}});
const DocImage=Image.extend({addAttributes(){return {...this.parent?.(),width:{default:100,parseHTML:el=>Number(el.getAttribute('data-width'))||100},align:{default:'center',parseHTML:el=>el.getAttribute('data-align')||'center'}};},renderHTML({HTMLAttributes:a}){return ['img',mergeAttributes(this.options.HTMLAttributes,a,{'data-width':a.width,'data-align':a.align,style:`width:${a.width}%;max-width:100%;height:auto;display:block;margin-left:${a.align==='left'?'0':'auto'};margin-right:${a.align==='right'?'0':'auto'}`})];}}).configure({allowBase64:true});
const StableIds=Extension.create({name:'stableHeadingIds',addGlobalAttributes(){return [{types:['heading'],attributes:{id:{default:null,parseHTML:el=>el.getAttribute('id'),renderHTML:a=>a.id?{id:a.id}:{}}}}];},addProseMirrorPlugins(){return [new Plugin({appendTransaction(transactions,old,state){if(!transactions.some(t=>t.docChanged))return null;const tr=state.tr,seen=new Set<string>();state.doc.descendants((node,pos)=>{if(node.type.name!=='heading')return;let id=node.attrs.id;if(!id||seen.has(id)){id='section-'+crypto.randomUUID();tr.setNodeMarkup(pos,undefined,{...node.attrs,id});}seen.add(id);});return tr.docChanged?tr:null;}})];}});
export function extensions(){return [StarterKit.configure({codeBlock:false,heading:{levels:[2,3,4,5,6]},link:{openOnClick:false,autolink:true,HTMLAttributes:{rel:'noopener noreferrer',target:'_blank'}}}),TextAlign.configure({types:['heading','paragraph']}),TableKit.configure({table:{resizable:true,allowTableNodeSelection:true}}),DocImage,Callout,DocButton,StableIds,CodeBlockLowlight.extend({addNodeView(){return ReactNodeViewRenderer(CodeView);}}).configure({lowlight:createLowlight(common),defaultLanguage:'text'})];}
